#!/usr/bin/env node

const execSync = require('child_process').execSync;
const statSync = require('fs').statSync;
const writeFileSync = require('fs').writeFileSync;

const THREE_MONTHS_IN_MS = 3 * 30 * 24 * 60 * 60 * 1000;

const albums = execSync('find /Volumes/Lossless/Lossless -type d -name \'[0-9][0-9][0-9][0-9] - *\'')
  .toString()
  .trim()
  .split('\n').sort((a, b) => statSync(b).birthtimeMs - statSync(a).birthtimeMs);

const albumsToInclude = [];
const songsToInclude = [];

albums.forEach((album) => {
  if (statSync(album).birthtimeMs > Date.now() - THREE_MONTHS_IN_MS) {
    albumsToInclude.push(album);
  }
});

albumsToInclude.forEach((album) => {
  const songs = execSync(`find "${album}" -type f -name '*.flac'`).toString().trim().split('\n');
  songsToInclude.push(songs[0]);
});

execSync("rm -rf /Volumes/Lossless/Lossless/recent.m3u");
execSync(`touch /Volumes/Lossless/Lossless/recent.m3u`);
writeFileSync("/Volumes/Lossless/Lossless/recent.m3u", songsToInclude.join('\n'));
