#!/usr/bin/env node

const execSync = require("child_process").execSync;
const existsSync = require("fs").existsSync;
const readdirSync = require("fs").readdirSync;
const readline = require("readline");


// constants
// ----------------------------------------------------------------------------

const tags = {
  artist: 'ARTIST',
  year: 'DATE',
  album: 'ALBUM',
  trackNumber: 'TRACKNUMBER',
  title: 'TITLE',
};

const validAnswers = new Set([
  'y',
  'yes',
  'Yes',
  'YES',
]);


// helpers
// ----------------------------------------------------------------------------

const checkForMetaflac = () => {
  try {
    execSync("which metaflac");
  }
  catch(err) {
    console.log("This script requires the `metaflac` package; install it with `brew install flac`.");
    process.exit(1);
  }
};

const getTargetFolder = () => {
  const scriptDir = process.argv[1].replace(/[^\/]+$/, '');
  const userDir = process.argv[2];

  if (!userDir) {
    console.error('You must pass a directory as the first argument.');
    process.exit(1);
  }

  const dir = userDir.indexOf("/") === 0
    ? userDir
    : `${process.cwd()}/${userDir}`;

  console.log(`Looking for flac files in ${dir}/`);

  if (!existsSync(dir)) {
    console.error('Error: that directory does not exist.');
    process.exit(1);
  }

  return dir;
};

const escapeFilename = (filename) => {
  return filename
    .replace(/ /g, "\\ ")
    .replace(/'/g, "\\'")
    .replace(/&/g, "\\&")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
};

const getFilenameFromFlac = (inputFile) => {
  const res = {};

  Object.keys(tags).forEach((key) => {
    const tagName = tags[key];
    const tag = execSync(`metaflac --show-tag=${tagName} ${inputFile}`)
      .toString()
      .trim()
      .replace(/^.+=/, '') // remove the tag format,  ARTICST=Deerhoof
      .replace('/', '-'); // remove invalid filename characters

    res[key] = tag;
  });

  return `${res.artist} - ${res.year} - ${res.album} - ${res.trackNumber} - ${res.title}.flac`;
};

const renameFiles = (dir, files) => {
  console.log('Renaming...');

  files.forEach((fileTuple) => {
    const cmd = [
      'mv',
      escapeFilename(`${dir}/${fileTuple[0]}`),
      escapeFilename(`${dir}/${fileTuple[1]}`),
    ].join(' ');

    execSync(cmd);
  });

  console.log('Done!');
  process.exit(0);
};

const removeArtwork = (dir) => {
  console.log('\nRemoving artwork...');

  const file = escapeFilename(`${dir}/*.flac`);
  execSync(`metaflac --preserve-modtime --remove --block-type=PICTURE --dont-use-padding ${file}`);
};

const removeAlbumArtist = (dir) => {
  console.log('Removing album artist...');

  const file = escapeFilename(`${dir}/*.flac`);
  execSync(`metaflac --preserve-modtime --remove-tag=ALBUMARTIST ${file}`);
};


// script
// ----------------------------------------------------------------------------

checkForMetaflac();

const renameStorage = [];
const dir = getTargetFolder();
const files = readdirSync(dir)
  .filter((file) => file.indexOf('.flac') > 0);

if (!files || !files.length) {
  console.error("No flac files found!");
  process.exit(1);
}

files.forEach((file) => {
  const newName = getFilenameFromFlac(escapeFilename(`${dir}/${file}`));
  renameStorage.push([file, newName])
});

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

console.log("\nHere are the proposed file names:");
console.log(renameStorage.map((item) => item[1]));

rl.question("\nWould you like to rename them? This will also remove any embedded artwork and album artist tags. [y/n] ", (answer) => {
  if (validAnswers.has(answer)) {
    removeArtwork(dir);
    removeAlbumArtist(dir);
    renameFiles(dir, renameStorage);
  } else {
    console.log("No action taken.");
  }

  rl.close();
  process.exit(0);
});
